### PR TITLE
Implement release resource import support

### PR DESCRIPTION
**Pull request by relu**

### CODE REVIEW

**Review by aaronmell — COMMENTED** [review]
This doesn't import any of the values from that chart? What happens on a subquent run?

**Comment by relu** [comment]
I've only had the chance to test this with really basic examples, will have to put a bit more effort into it and also update the tests for sure. Should have probably submitted it as a draft PR now that I think about it.

**Comment by aaronmell** [comment]
Okay, I'll leave it open until you think its ready to be merged in.

**Comment by relu** [comment]
Closing in favour of upstream PR: https://github.com/terraform-providers/terraform-provider-helm/pull/394

**Pull request closed without merging**
